
export const numberOfCardsForTag = {
        "Basic Land":6,
        "Snow Basic Land":6,
        "Command Tower / Exotic Orchard":2,
        "Fetch Land":10,
        "Prismatic Vista / Fabled Passage":2,
        "Shock Land":10, 
        "Bond Land":10, 
        "Slow Land":10, 
        "Fast Land":10, 
        "Fetchable Tri Land":11, 
        "Non-Fetchable Tri Land":10, 
        "Pain Land":10, 
        "City of Brass / Mana Confluence":2,
        "Canopy Land":6, 
        "Two Color Bounce Land":10,
        "Mono Color Bounce Land":7,  
        "Check Land":10, 
        "Hybrid Filter Land":10, 
        "Odyssey Filter Land":10, 
        "Dual Land":10, 
        "Scry Land":10, 
        "Tango Land":5,
        "Surveil Land":10,
        "Gate Land":23,
        "Cave Land":20,
        "Urza Tron Land":3,
    }