export const hardCodedTagNames = {
    "Basic Land":[{"name":"Forest","cId":["G"]},{"name":"Island","cId":["U"]},{"name":"Mountain","cId":["R"]},{"name":"Plains","cId":["W"]},{"name":"Swamp","cId":["B"]},{"name":"Wastes","cId":[]}],
    "Snow Basic Land":[{"name":"Snow-Covered Forest","cId":["G"]},{"name":"Snow-Covered Island","cId":["U"]},{"name":"Snow-Covered Mountain","cId":["R"]},{"name":"Snow-Covered Plains","cId":["W"]},{"name":"Snow-Covered Swamp","cId":["B"]},{"name":"Snow-Covered Wastes","cId":[]}],
    "Mono Castle Land":[{"name":"Castle Ardenvale","cId":["W"]},{"name":"Castle Embereth","cId":["R"]},{"name":"Castle Garenbrig","cId":["G"]},{"name":"Castle Locthwain","cId":["B"]},{"name":"Castle Vantress","cId":["U"]}],
    "Any Color Color Fix":[{"name":"Abandoned Outpost","cId":["W"]},{"name":"A-Base Camp","cId":[]},{"name":"Aether Hub","cId":[]},{"name":"Ancient Ziggurat","cId":[]},{"name":"Archaeological Dig","cId":[]},{"name":"Archway Commons","cId":[]},{"name":"Base Camp","cId":[]},{"name":"Bog Wreckage","cId":["B"]},{"name":"Brotherhood Headquarters","cId":[]},{"name":"Cavern of Souls","cId":[]},{"name":"City of Brass","cId":[]},{"name":"Command Tower","cId":[]},{"name":"Corrupted Crossroads","cId":[]},{"name":"Crumbling Vestige","cId":[]},{"name":"Exotic Orchard","cId":[]},{"name":"Fabled Passage","cId":[]},{"name":"Forbidden Orchard","cId":[]},{"name":"Forgotten Monument","cId":[]},{"name":"Forsaken City","cId":[]},{"name":"Gallifrey Council Chamber","cId":[]},{"name":"Gateway Plaza","cId":[]},{"name":"Gemstone Caverns","cId":[]},{"name":"Gemstone Mine","cId":[]},{"name":"Glimmervoid","cId":[]},{"name":"Gond Gate","cId":[]},{"name":"Grand Coliseum","cId":[]},{"name":"Hadana's Climb // Winged Temple of Orazca","cId":["G","U"]},{"name":"Holdout Settlement","cId":[]},{"name":"Journey to Eternity // Atzal, Cave of Eternity","cId":["B","G"]},{"name":"Mana Confluence","cId":[]},{"name":"Mirrodin's Core","cId":[]},{"name":"Paliano, the High City","cId":[]},{"name":"Path of Ancestry","cId":[]},{"name":"Path of Mettle // Metzali, Tower of Triumph","cId":["R","W"]},{"name":"Pillar of the Paruns","cId":[]},{"name":"Power Depot","cId":[]},{"name":"Primal Amulet // Primal Wellspring","cId":[]},{"name":"Primal Beyond","cId":[]},{"name":"Prismatic Vista","cId":[]},{"name":"Profane Procession // Tomb of the Dusk Rose","cId":["B","W"]},{"name":"Public Thoroughfare","cId":[]},{"name":"Rainbow Vale","cId":[]},{"name":"Ravaged Highlands","cId":["R"]},{"name":"Rupture Spire","cId":[]},{"name":"Scene of the Crime","cId":[]},{"name":"Seafloor Debris","cId":["U"]},{"name":"Secluded Courtyard","cId":[]},{"name":"Secret Base","cId":[]},{"name":"Spire of Industry","cId":[]},{"name":"Starting Town","cId":[]},{"name":"Storm the Vault // Vault of Catlacan","cId":["R","U"]},{"name":"Survivors' Encampment","cId":[]},{"name":"Tarnished Citadel","cId":[]},{"name":"Tendo Ice Bridge","cId":[]},{"name":"The Big Top","cId":[]},{"name":"The Grey Havens","cId":[]},{"name":"The Seedcore","cId":[]},{"name":"The World Tree","cId":["B","G","R","U","W"]},{"name":"Thran Quarry","cId":[]},{"name":"Timberland Ruins","cId":["G"]},{"name":"Transguild Promenade","cId":[]},{"name":"Unclaimed Territory","cId":[]},{"name":"Underdome","cId":[]},{"name":"Undiscovered Paradise","cId":[]},{"name":"Vivid Crag","cId":["R"]},{"name":"Vivid Creek","cId":["U"]},{"name":"Vivid Grove","cId":["G"]},{"name":"Vivid Marsh","cId":["B"]},{"name":"Vivid Meadow","cId":["W"]}],
    "Mono Lord of the Rings Land":[{"name":"Barad-dûr","cId":["B"]},{"name":"Minas Tirith","cId":["W"]},{"name":"Mines of Moria","cId":["R"]},{"name":"Rivendell","cId":["U"]},{"name":"The Shire","cId":["G"]}],
    "Mono MDFC Land":[{"name":"Agadeem's Awakening // Agadeem, the Undercrypt","cId":["B"]},{"name":"Akoum Warrior // Akoum Teeth","cId":["R"]},{"name":"Bala Ged Recovery // Bala Ged Sanctuary","cId":["G"]},{"name":"Beyeen Veil // Beyeen Coast","cId":["U"]},{"name":"Blackbloom Rogue // Blackbloom Bog","cId":["B"]},{"name":"Boggart Trawler // Boggart Bog","cId":["B"]},{"name":"Bridgeworks Battle // Tanglespan Bridgeworks","cId":["G"]},{"name":"Disciple of Freyalise // Garden of Freyalise","cId":["G"]},{"name":"Emeria's Call // Emeria, Shattered Skyclave","cId":["W"]},{"name":"Fell the Profane // Fell Mire","cId":["B"]},{"name":"Glasspool Mimic // Glasspool Shore","cId":["U"]},{"name":"Hagra Mauling // Hagra Broodpit","cId":["B"]},{"name":"Hydroelectric Specimen // Hydroelectric Laboratory","cId":["U"]},{"name":"Jwari Disruption // Jwari Ruins","cId":["U"]},{"name":"Kabira Takedown // Kabira Plateau","cId":["W"]},{"name":"Kazandu Mammoth // Kazandu Valley","cId":["G"]},{"name":"Kazuul's Fury // Kazuul's Cliffs","cId":["R"]},{"name":"Khalni Ambush // Khalni Territory","cId":["G"]},{"name":"Makindi Stampede // Makindi Mesas","cId":["W"]},{"name":"Malakir Rebirth // Malakir Mire","cId":["B"]},{"name":"Ondu Inversion // Ondu Skyruins","cId":["W"]},{"name":"Pelakka Predation // Pelakka Caverns","cId":["B"]},{"name":"Pinnacle Monk // Mystic Peak","cId":["R"]},{"name":"Razorgrass Ambush // Razorgrass Field","cId":["W"]},{"name":"Sea Gate Restoration // Sea Gate, Reborn","cId":["U"]},{"name":"Sejiri Shelter // Sejiri Glacier","cId":["W"]},{"name":"Shatterskull Smashing // Shatterskull, the Hammer Pass","cId":["R"]},{"name":"Silundi Vision // Silundi Isle","cId":["U"]},{"name":"Sink into Stupor // Soporific Springs","cId":["U"]},{"name":"Skyclave Cleric // Skyclave Basilica","cId":["W"]},{"name":"Song-Mad Treachery // Song-Mad Ruins","cId":["R"]},{"name":"Spikefield Hazard // Spikefield Cave","cId":["R"]},{"name":"Sundering Eruption // Volcanic Fissure","cId":["R"]},{"name":"Tangled Florahedron // Tangled Vale","cId":["G"]},{"name":"Turntimber Symbiosis // Turntimber, Serpentine Wood","cId":["G"]},{"name":"Umara Wizard // Umara Skyfalls","cId":["U"]},{"name":"Valakut Awakening // Valakut Stoneforge","cId":["R"]},{"name":"Vastwood Fortification // Vastwood Thicket","cId":["G"]},{"name":"Witch Enchanter // Witch-Blessed Meadow","cId":["W"]},{"name":"Zof Consumption // Zof Bloodbog","cId":["B"]}],
    "Mono Modern Horizon 3 Land":[{"name":"Archway of Innovation","cId":["U"]},{"name":"Arena of Glory","cId":["R"]},{"name":"Monumental Henge","cId":["W"]},{"name":"Shifting Woodland","cId":["G"]},{"name":"Spymaster's Vault","cId":["B"]}],
    "Mono Kamigawa Land":[{"name":"Boseiju, Who Endures","cId":["G"]},{"name":"Eiganjo Castle","cId":["W"]},{"name":"Eiganjo, Seat of the Empire","cId":["W"]},{"name":"Minamo, School at Water's Edge","cId":["U"]},{"name":"Okina, Temple to the Grandfathers","cId":["G"]},{"name":"Otawara, Soaring City","cId":["U"]},{"name":"Shinka, the Bloodsoaked Keep","cId":["R"]},{"name":"Shizo, Death's Storehouse","cId":["B"]},{"name":"Sokenzan, Crucible of Defiance","cId":["R"]},{"name":"Takenuma, Abandoned Mire","cId":["B"]}],
    "Dual Bounce Land":[{"name":"Azorius Chancery","cId":["U","W"]},{"name":"Boros Garrison","cId":["R","W"]},{"name":"Dimir Aqueduct","cId":["B","U"]},{"name":"Golgari Rot Farm","cId":["B","G"]},{"name":"Gruul Turf","cId":["G","R"]},{"name":"Izzet Boilerworks","cId":["R","U"]},{"name":"Orzhov Basilica","cId":["B","W"]},{"name":"Rakdos Carnarium","cId":["B","R"]},{"name":"Selesnya Sanctuary","cId":["G","W"]},{"name":"Simic Growth Chamber","cId":["G","U"]}],
    "Dual Bond Land":[{"name":"Bountiful Promenade","cId":["G","W"]},{"name":"Luxury Suite","cId":["B","R"]},{"name":"Morphic Pool","cId":["B","U"]},{"name":"Rejuvenating Springs","cId":["G","U"]},{"name":"Sea of Clouds","cId":["U","W"]},{"name":"Spectator Seating","cId":["R","W"]},{"name":"Spire Garden","cId":["G","R"]},{"name":"Training Center","cId":["R","U"]},{"name":"Undergrowth Stadium","cId":["B","G"]},{"name":"Vault of Champions","cId":["B","W"]}],
    "Dual Canopy Land":[{"name":"Fiery Islet","cId":["R","U"]},{"name":"Horizon Canopy","cId":["G","W"]},{"name":"Nurturing Peatland","cId":["B","G"]},{"name":"Silent Clearing","cId":["B","W"]},{"name":"Sunbaked Canyon","cId":["R","W"]},{"name":"Waterlogged Grove","cId":["G","U"]}],
    "Dual Check Land":[{"name":"Clifftop Retreat","cId":["R","W"]},{"name":"Dragonskull Summit","cId":["B","R"]},{"name":"Drowned Catacomb","cId":["B","U"]},{"name":"Glacial Fortress","cId":["U","W"]},{"name":"Hinterland Harbor","cId":["G","U"]},{"name":"Isolated Chapel","cId":["B","W"]},{"name":"Rootbound Crag","cId":["G","R"]},{"name":"Sulfur Falls","cId":["R","U"]},{"name":"Sunpetal Grove","cId":["G","W"]},{"name":"Woodland Cemetery","cId":["B","G"]}],
    "Dual Pain Land":[{"name":"Adarkar Wastes","cId":["U","W"]},{"name":"Battlefield Forge","cId":["R","W"]},{"name":"Brushland","cId":["G","W"]},{"name":"Caves of Koilos","cId":["B","W"]},{"name":"Karplusan Forest","cId":["G","R"]},{"name":"Llanowar Wastes","cId":["B","G"]},{"name":"Shivan Reef","cId":["R","U"]},{"name":"Sulfurous Springs","cId":["B","R"]},{"name":"Underground River","cId":["B","U"]},{"name":"Yavimaya Coast","cId":["G","U"]}],
    "Dual Fetch Land":[{"name":"Arid Mesa","cId":[]},{"name":"Bloodstained Mire","cId":[]},{"name":"Flooded Strand","cId":[]},{"name":"Marsh Flats","cId":[]},{"name":"Misty Rainforest","cId":[]},{"name":"Polluted Delta","cId":[]},{"name":"Scalding Tarn","cId":[]},{"name":"Verdant Catacombs","cId":[]},{"name":"Windswept Heath","cId":[]},{"name":"Wooded Foothills","cId":[]}],
    "Dual Hybrid Filter Land":[{"name":"Cascade Bluffs","cId":["R","U"]},{"name":"Fetid Heath","cId":["B","W"]},{"name":"Fire-Lit Thicket","cId":["G","R"]},{"name":"Flooded Grove","cId":["G","U"]},{"name":"Graven Cairns","cId":["B","R"]},{"name":"Mystic Gate","cId":["U","W"]},{"name":"Rugged Prairie","cId":["R","W"]},{"name":"Sunken Ruins","cId":["B","U"]},{"name":"Twilight Mire","cId":["B","G"]},{"name":"Wooded Bastion","cId":["G","W"]}],
    "Dual MDFC Land":[{"name":"Barkchannel Pathway // Tidechannel Pathway","cId":["G","U"]},{"name":"Blightstep Pathway // Searstep Pathway","cId":["B","R"]},{"name":"Bloodsoaked Insight // Sanguine Morass","cId":["B","R"]},{"name":"Branchloft Pathway // Boulderloft Pathway","cId":["G","W"]},{"name":"Brightclimb Pathway // Grimclimb Pathway","cId":["B","W"]},{"name":"Clearwater Pathway // Murkwater Pathway","cId":["B","U"]},{"name":"Cragcrown Pathway // Timbercrown Pathway","cId":["G","R"]},{"name":"Darkbore Pathway // Slitherbore Pathway","cId":["B","G"]},{"name":"Drowner of Truth // Drowned Jungle","cId":["G","U"]},{"name":"Glasswing Grace // Age-Graced Chapel","cId":["B","W"]},{"name":"Hengegate Pathway // Mistgate Pathway","cId":["U","W"]},{"name":"Legion Leadership // Legion Stronghold","cId":["R","W"]},{"name":"Needleverge Pathway // Pillarverge Pathway","cId":["R","W"]},{"name":"Revitalizing Repast // Old-Growth Grove","cId":["B","G"]},{"name":"Riverglide Pathway // Lavaglide Pathway","cId":["R","U"]},{"name":"Rush of Inspiration // Crackling Falls","cId":["R","U"]},{"name":"Strength of the Harvest // Haven of the Harvest","cId":["G","W"]},{"name":"Stump Stomp // Burnwillow Clearing","cId":["G","R"]},{"name":"Suppression Ray // Orderly Plaza","cId":["U","W"]},{"name":"Waterlogged Teachings // Inundated Archive","cId":["B","U"]}],
    "Dual Scry Land":[{"name":"Temple of Abandon","cId":["G","R"]},{"name":"Temple of Deceit","cId":["B","U"]},{"name":"Temple of Enlightenment","cId":["U","W"]},{"name":"Temple of Epiphany","cId":["R","U"]},{"name":"Temple of Malady","cId":["B","G"]},{"name":"Temple of Malice","cId":["B","R"]},{"name":"Temple of Mystery","cId":["G","U"]},{"name":"Temple of Plenty","cId":["G","W"]},{"name":"Temple of Silence","cId":["B","W"]},{"name":"Temple of Triumph","cId":["R","W"]}],
    "Dual Shock Land":[{"name":"Blood Crypt","cId":["B","R"]},{"name":"Breeding Pool","cId":["G","U"]},{"name":"Godless Shrine","cId":["B","W"]},{"name":"Hallowed Fountain","cId":["U","W"]},{"name":"Overgrown Tomb","cId":["B","G"]},{"name":"Sacred Foundry","cId":["R","W"]},{"name":"Steam Vents","cId":["R","U"]},{"name":"Stomping Ground","cId":["G","R"]},{"name":"Temple Garden","cId":["G","W"]},{"name":"Watery Grave","cId":["B","U"]}],
    "Dual Slow Land":[{"name":"Deathcap Glade","cId":["B","G"]},{"name":"Deserted Beach","cId":["U","W"]},{"name":"Dreamroot Cascade","cId":["G","U"]},{"name":"Haunted Ridge","cId":["B","R"]},{"name":"Overgrown Farmland","cId":["G","W"]},{"name":"Rockfall Vale","cId":["G","R"]},{"name":"Shattered Sanctum","cId":["B","W"]},{"name":"Shipwreck Marsh","cId":["B","U"]},{"name":"Stormcarved Coast","cId":["R","U"]},{"name":"Sundown Pass","cId":["R","W"]}],
    "Dual Surveil Land":[{"name":"Commercial District","cId":["G","R"]},{"name":"Elegant Parlor","cId":["R","W"]},{"name":"Hedge Maze","cId":["G","U"]},{"name":"Lush Portico","cId":["G","W"]},{"name":"Meticulous Archive","cId":["U","W"]},{"name":"Raucous Theater","cId":["B","R"]},{"name":"Shadowy Backstreet","cId":["B","W"]},{"name":"Thundering Falls","cId":["R","U"]},{"name":"Undercity Sewers","cId":["B","U"]},{"name":"Underground Mortuary","cId":["B","G"]}],
    "Tri Land (Fetchable)":[{"name":"Indatha Triome","cId":["B","G","W"]},{"name":"Jetmir's Garden","cId":["G","R","W"]},{"name":"Ketria Triome","cId":["G","R","U"]},{"name":"Murmuring Bosk","cId":["B","G","W"]},{"name":"Raffine's Tower","cId":["B","U","W"]},{"name":"Raugrin Triome","cId":["R","U","W"]},{"name":"Savai Triome","cId":["B","R","W"]},{"name":"Spara's Headquarters","cId":["G","U","W"]},{"name":"Xander's Lounge","cId":["B","R","U"]},{"name":"Zagoth Triome","cId":["B","G","U"]},{"name":"Ziatora's Proving Ground","cId":["B","G","R"]}],
    "Tri Land (Non-Fetchable)":[{"name":"Arcane Sanctum","cId":["B","U","W"]},{"name":"Crumbling Necropolis","cId":["B","R","U"]},{"name":"Frontier Bivouac","cId":["G","R","U"]},{"name":"Jungle Shrine","cId":["G","R","W"]},{"name":"Mystic Monastery","cId":["R","U","W"]},{"name":"Nomad Outpost","cId":["B","R","W"]},{"name":"Opulent Palace","cId":["B","G","U"]},{"name":"Sandsteppe Citadel","cId":["B","G","W"]},{"name":"Savage Lands","cId":["B","G","R"]},{"name":"Seaside Citadel","cId":["G","U","W"]},{"name":"Tournament Grounds","cId":["B","R","W"]}],
    "Mono Adventures Slow Land":[{"name":"Cave of the Frost Dragon","cId":["W"]},{"name":"Den of the Bugbear","cId":["R"]},{"name":"Hall of Storm Giants","cId":["U"]},{"name":"Hive of the Eye Tyrant","cId":["B"]},{"name":"Lair of the Hydra","cId":["G"]}],
    "Mono Aetherdrift Land":[{"name":"Country Roads","cId":["W"]},{"name":"Foul Roads","cId":["B"]},{"name":"Reef Roads","cId":["U"]},{"name":"Rocky Roads","cId":["R"]},{"name":"Wild Roads","cId":["G"]}],
    "Mono Alliances Land":[{"name":"Balduvian Trading Post","cId":["R"]},{"name":"Heart of Yavimaya","cId":["G"]},{"name":"Kjeldoran Outpost","cId":["W"]},{"name":"Lake of the Dead","cId":["B"]},{"name":"Soldevi Excavations","cId":["U"]}],
    "Mono Bloomburrow Land":[{"name":"Lilypad Village","cId":["U"]},{"name":"Lupinflower Village","cId":["W"]},{"name":"Mudflat Village","cId":["B"]},{"name":"Oakhollow Village","cId":["G"]},{"name":"Rockface Village","cId":["R"]}],
    "Mono Dominaria Land":[{"name":"Memorial to Folly","cId":["B"]},{"name":"Memorial to Genius","cId":["U"]},{"name":"Memorial to Glory","cId":["W"]},{"name":"Memorial to Unity","cId":["G"]},{"name":"Memorial to War","cId":["R"]}],
    "Mono Eldrane Fetchable Land":[{"name":"Dwarven Mine","cId":["R"]},{"name":"Gingerbread Cabin","cId":["G"]},{"name":"Idyllic Grange","cId":["W"]},{"name":"Mystic Sanctuary","cId":["U"]},{"name":"Witch's Cottage","cId":["B"]}],
    "Mono Dragonstorm Check Land":[{"name":"Cori Mountain Monastery","cId":["R"]},{"name":"Dalkovan Encampment","cId":["W"]},{"name":"Great Arashin City","cId":["B"]},{"name":"Kishla Village","cId":["G"]},{"name":"Mistrise Village","cId":["U"]}],
    "Mono Fallen Empires Land":[{"name":"Bottomless Vault","cId":["B"]},{"name":"Dwarven Hold","cId":["R"]},{"name":"Dwarven Ruins","cId":["R"]},{"name":"Ebon Stronghold","cId":["B"]},{"name":"Havenwood Battleground","cId":["G"]},{"name":"Hollow Trees","cId":["G"]},{"name":"Icatian Store","cId":["W"]},{"name":"Ruins of Trokair","cId":["W"]},{"name":"Sand Silos","cId":["U"]},{"name":"Svyelunite Temple","cId":["U"]}],
    "Mono Hour of Devastation Land":[{"name":"Memorial to Folly","cId":["B"]},{"name":"Memorial to Genius","cId":["U"]},{"name":"Memorial to Glory","cId":["W"]},{"name":"Memorial to Unity","cId":["G"]},{"name":"Memorial to War","cId":["R"]}],
    "Mono Ixalan Cave Land":[{"name":"Hidden Cataract","cId":["U"]},{"name":"Hidden Courtyard","cId":["W"]},{"name":"Hidden Necropolis","cId":["B"]},{"name":"Hidden Nursery","cId":["G"]},{"name":"Hidden Volcano","cId":["R"]}],
    "Mono Legends Land":[{"name":"Hammerheim","cId":["R"]},{"name":"Karakas","cId":["W"]},{"name":"Pendelhaven","cId":["G"]},{"name":"Tolaria","cId":["U"]},{"name":"Urborg","cId":["B"]}],
    "Mono Lorwyn Land":[{"name":"Howltooth Hollow","cId":["B"]},{"name":"Mosswort Bridge","cId":["G"]},{"name":"Shelldock Isle","cId":["U"]},{"name":"Spinerock Knoll","cId":["R"]},{"name":"Windbrisk Heights","cId":["W"]}],
    "Mono Mercadian Masques Land":[{"name":"Fountain of Cho","cId":["W"]},{"name":"Hickory Woodlot","cId":["G"]},{"name":"Mercadian Bazaar","cId":["R"]},{"name":"Peat Bog","cId":["B"]},{"name":"Remote Farm","cId":["W"]},{"name":"Rushwood Grove","cId":["G"]},{"name":"Sandstone Needle","cId":["R"]},{"name":"Saprazzan Cove","cId":["U"]},{"name":"Saprazzan Skerry","cId":["U"]},{"name":"Subterranean Hangar","cId":["B"]}],
    "Mono Mirroden Artifact Land":[{"name":"Ancient Den","cId":["W"]},{"name":"Great Furnace","cId":["R"]},{"name":"Seat of the Synod","cId":["U"]},{"name":"Tree of Tales","cId":["G"]},{"name":"Vault of Whispers","cId":["B"]}],
    "Mono Onslaught Cycling Land":[{"name":"Barren Moor","cId":["B"]},{"name":"Forgotten Cave","cId":["R"]},{"name":"Lonely Sandbar","cId":["U"]},{"name":"Secluded Steppe","cId":["W"]},{"name":"Tranquil Thicket","cId":["G"]}],
    "Mono Odyssey Land":[{"name":"Abandoned Outpost","cId":["W"]},{"name":"Barbarian Ring","cId":["R"]},{"name":"Bog Wreckage","cId":["B"]},{"name":"Cabal Pit","cId":["B"]},{"name":"Centaur Garden","cId":["G"]},{"name":"Cephalid Coliseum","cId":["U"]},{"name":"Nomad Stadium","cId":["W"]},{"name":"Ravaged Highlands","cId":["R"]},{"name":"Seafloor Debris","cId":["U"]},{"name":"Timberland Ruins","cId":["G"]}],
    "Mono Phyrexia Sphere Land":[{"name":"The Autonomous Furnace","cId":["R"]},{"name":"The Dross Pits","cId":["B"]},{"name":"The Fair Basilica","cId":["W"]},{"name":"The Hunter Maze","cId":["G"]},{"name":"The Surgical Bay","cId":["U"]}],
    "Mono Shadowmoor Fetchable Land":[{"name":"Leechridden Swamp","cId":["B"]},{"name":"Madblind Mountain","cId":["R"]},{"name":"Mistveil Plains","cId":["W"]},{"name":"Moonring Island","cId":["U"]},{"name":"Sapseep Forest","cId":["G"]}],
    "Mono Urza's Saga Land":[{"name":"Drifting Meadow","cId":["W"]},{"name":"Gaea's Cradle","cId":["G"]},{"name":"Phyrexian Tower","cId":["B"]},{"name":"Polluted Mire","cId":["B"]},{"name":"Remote Isle","cId":["U"]},{"name":"Serra's Sanctum","cId":["W"]},{"name":"Shivan Gorge","cId":["R"]},{"name":"Slippery Karst","cId":["G"]},{"name":"Smoldering Crater","cId":["R"]},{"name":"Tolarian Academy","cId":["U"]}],
    "Mono Visions Bounce Land":[{"name":"Arid Archway","cId":[]},{"name":"Coral Atoll","cId":["U"]},{"name":"Dormant Volcano","cId":["R"]},{"name":"Everglades","cId":["B"]},{"name":"Guildless Commons","cId":[]},{"name":"Jungle Basin","cId":["G"]},{"name":"Karoo","cId":["W"]}],
    "Mono Worldwake Land":[{"name":"Bojuka Bog","cId":["B"]},{"name":"Halimar Depths","cId":["U"]},{"name":"Khalni Garden","cId":["G"]},{"name":"Sejiri Steppe","cId":["W"]},{"name":"Smoldering Spires","cId":["R"]}],
    "Mono Zendikar Land":[{"name":"Crypt of Agadeem","cId":["B"]},{"name":"Emeria, the Sky Ruin","cId":["W"]},{"name":"Fertile Thicket","cId":["G"]},{"name":"Kabira Crossroads","cId":["W"]},{"name":"Looming Spires","cId":["R"]},{"name":"Magosi, the Waterveil","cId":["U"]},{"name":"Mortuary Mire","cId":["B"]},{"name":"Oran-Rief, the Vastwood","cId":["G"]},{"name":"Piranha Marsh","cId":["B"]},{"name":"Sandstone Bridge","cId":["W"]},{"name":"Skyline Cascade","cId":["U"]},{"name":"Soaring Seacliff","cId":["U"]},{"name":"Teetering Peaks","cId":["R"]},{"name":"Turntimber Grove","cId":["G"]},{"name":"Valakut, the Molten Pinnacle","cId":["R"]}],
    "Dual Artifact Land":[{"name":"Balamb Garden, SeeD Academy // Balamb Garden, Airborne","cId":["G","U"]},{"name":"Darkmoss Bridge","cId":["B","G"]},{"name":"Drossforge Bridge","cId":["B","R"]},{"name":"Goldmire Bridge","cId":["B","W"]},{"name":"Mistvault Bridge","cId":["B","U"]},{"name":"Razortide Bridge","cId":["U","W"]},{"name":"Rustvale Bridge","cId":["R","W"]},{"name":"Silverbluff Bridge","cId":["R","U"]},{"name":"Slagwoods Bridge","cId":["G","R"]},{"name":"Tanglepool Bridge","cId":["G","U"]},{"name":"Thornglint Bridge","cId":["G","W"]}],
    "Dual Bicycle Land":[{"name":"Canyon Slough","cId":["B","R"]},{"name":"Fetid Pools","cId":["B","U"]},{"name":"Irrigated Farmland","cId":["U","W"]},{"name":"Scattered Groves","cId":["G","W"]},{"name":"Sheltered Thicket","cId":["G","R"]}],
    "Dual Campus Land":[{"name":"Lorehold Campus","cId":["R","W"]},{"name":"Prismari Campus","cId":["R","U"]},{"name":"Quandrix Campus","cId":["G","U"]},{"name":"Silverquill Campus","cId":["B","W"]},{"name":"Witherbloom Campus","cId":["B","G"]}],
    "Dual Creature Land":[{"name":"Celestial Colonnade","cId":["U","W"]},{"name":"Creeping Tar Pit","cId":["B","U"]},{"name":"Hissing Quagmire","cId":["B","G"]},{"name":"Lavaclaw Reaches","cId":["B","R"]},{"name":"Lumbering Falls","cId":["G","U"]},{"name":"Needle Spires","cId":["R","W"]},{"name":"Raging Ravine","cId":["G","R"]},{"name":"Restless Anchorage","cId":["U","W"]},{"name":"Restless Bivouac","cId":["R","W"]},{"name":"Restless Cottage","cId":["B","G"]},{"name":"Restless Fortress","cId":["B","W"]},{"name":"Restless Prairie","cId":["G","W"]},{"name":"Restless Reef","cId":["B","U"]},{"name":"Restless Ridgeline","cId":["G","R"]},{"name":"Restless Spire","cId":["R","U"]},{"name":"Restless Vents","cId":["B","R"]},{"name":"Restless Vinestalk","cId":["G","U"]},{"name":"Shambling Vent","cId":["B","W"]},{"name":"Stirring Wildwood","cId":["G","W"]},{"name":"Wandering Fumarole","cId":["R","U"]}],
    "Dual Deplete Land":[{"name":"Land Cap","cId":["U","W"]},{"name":"Lava Tubes","cId":["B","R"]},{"name":"River Delta","cId":["B","U"]},{"name":"Timberline Ridge","cId":["G","R"]},{"name":"Veldt","cId":["G","W"]}],
    "Dual Desert Ping Land":[{"name":"Abraded Bluffs","cId":["R","W"]},{"name":"Bristling Backwoods","cId":["G","R"]},{"name":"Creosote Heath","cId":["G","W"]},{"name":"Eroded Canyon","cId":["R","U"]},{"name":"Festering Gulch","cId":["B","G"]},{"name":"Forlorn Flats","cId":["B","W"]},{"name":"Jagged Barrens","cId":["B","R"]},{"name":"Lonely Arroyo","cId":["U","W"]},{"name":"Lush Oasis","cId":["G","U"]},{"name":"Soured Springs","cId":["B","U"]}],
    "Dual Fast Land":[{"name":"Blackcleave Cliffs","cId":["B","R"]},{"name":"Blooming Marsh","cId":["B","G"]},{"name":"Botanical Sanctum","cId":["G","U"]},{"name":"Concealed Courtyard","cId":["B","W"]},{"name":"Copperline Gorge","cId":["G","R"]},{"name":"Darkslick Shores","cId":["B","U"]},{"name":"Inspiring Vantage","cId":["R","W"]},{"name":"Razorverge Thicket","cId":["G","W"]},{"name":"Seachrome Coast","cId":["U","W"]},{"name":"Spirebluff Canal","cId":["R","U"]}],
    "Dual Fetchable Snow Land":[{"name":"Alpine Meadow","cId":["R","W"]},{"name":"Arctic Treeline","cId":["G","W"]},{"name":"Glacial Floodplain","cId":["U","W"]},{"name":"Highland Forest","cId":["G","R"]},{"name":"Ice Tunnel","cId":["B","U"]},{"name":"Rimewood Falls","cId":["G","U"]},{"name":"Snowfield Sinkhole","cId":["B","W"]},{"name":"Sulfurous Mire","cId":["B","R"]},{"name":"Volatile Fjord","cId":["R","U"]},{"name":"Woodland Chasm","cId":["B","G"]}],
    "Dual Fetchable Tapped Land":[{"name":"Contaminated Aquifer","cId":["B","U"]},{"name":"Geothermal Bog","cId":["B","R"]},{"name":"Haunted Mire","cId":["B","G"]},{"name":"Idyllic Beachfront","cId":["U","W"]},{"name":"Molten Tributary","cId":["R","U"]},{"name":"Radiant Grove","cId":["G","W"]},{"name":"Sacred Peaks","cId":["R","W"]},{"name":"Sunlit Marsh","cId":["B","W"]},{"name":"Tangled Islet","cId":["G","U"]},{"name":"Wooded Ridgeline","cId":["G","R"]}],
    "Dual Gain Land":[{"name":"Bloodfell Caves","cId":["B","R"]},{"name":"Blossoming Sands","cId":["G","W"]},{"name":"Dismal Backwater","cId":["B","U"]},{"name":"Jungle Hollow","cId":["B","G"]},{"name":"Rugged Highlands","cId":["G","R"]},{"name":"Scoured Barrens","cId":["B","W"]},{"name":"Swiftwater Cliffs","cId":["R","U"]},{"name":"Thornwood Falls","cId":["G","U"]},{"name":"Tranquil Cove","cId":["U","W"]},{"name":"Wind-Scarred Crag","cId":["R","W"]}],
    "Dual Guild Gate Land":[{"name":"Azorius Guildgate","cId":["U","W"]},{"name":"Boros Guildgate","cId":["R","W"]},{"name":"Dimir Guildgate","cId":["B","U"]},{"name":"Golgari Guildgate","cId":["B","G"]},{"name":"Gruul Guildgate","cId":["G","R"]},{"name":"Izzet Guildgate","cId":["R","U"]},{"name":"Orzhov Guildgate","cId":["B","W"]},{"name":"Rakdos Guildgate","cId":["B","R"]},{"name":"Selesnya Guildgate","cId":["G","W"]},{"name":"Simic Guildgate","cId":["G","U"]}],
    "Dual Horizon Land":[{"name":"Fiery Islet","cId":["R","U"]},{"name":"Horizon Canopy","cId":["G","W"]},{"name":"Nurturing Peatland","cId":["B","G"]},{"name":"Silent Clearing","cId":["B","W"]},{"name":"Sunbaked Canyon","cId":["R","W"]},{"name":"Waterlogged Grove","cId":["G","U"]}],
    "Dual Kamigawa Land":[{"name":"Cloudcrest Lake","cId":["U","W"]},{"name":"Lantern-Lit Graveyard","cId":["B","R"]},{"name":"Pinecrest Ridge","cId":["G","R"]},{"name":"Tranquil Garden","cId":["G","W"]},{"name":"Waterveil Cavern","cId":["B","U"]}],
    "Dual Kindred Land":[{"name":"Ancient Amphitheater","cId":["R","W"]},{"name":"Auntie's Hovel","cId":["B","R"]},{"name":"Gilt-Leaf Palace","cId":["B","G"]},{"name":"Secluded Glen","cId":["B","U"]},{"name":"Wanderwine Hub","cId":["U","W"]}],
    "Dual Land":[{"name":"Badlands","cId":["B","R"]},{"name":"Bayou","cId":["B","G"]},{"name":"Plateau","cId":["R","W"]},{"name":"Savannah","cId":["G","W"]},{"name":"Scrubland","cId":["B","W"]},{"name":"Taiga","cId":["G","R"]},{"name":"Tropical Island","cId":["G","U"]},{"name":"Tundra","cId":["U","W"]},{"name":"Underground Sea","cId":["B","U"]},{"name":"Volcanic Island","cId":["R","U"]}],
    "Dual Land (Extras)":[{"name":"Fortified Beachhead","cId":["U","W"]},{"name":"Grove of the Burnwillows","cId":["G","R"]},{"name":"Krosan Verge","cId":[]},{"name":"Mount Doom","cId":["B","R"]},{"name":"Nimbus Maze","cId":["U","W"]},{"name":"River of Tears","cId":["B","U"]}],
    "Dual Odyssey Filter Land":[{"name":"Darkwater Catacombs","cId":["B","U"]},{"name":"Desolate Mire","cId":["B","W"]},{"name":"Ferrous Lake","cId":["R","U"]},{"name":"Mossfire Valley","cId":["G","R"]},{"name":"Overflowing Basin","cId":["G","U"]},{"name":"Shadowblood Ridge","cId":["B","R"]},{"name":"Skycloud Expanse","cId":["U","W"]},{"name":"Sungrass Prairie","cId":["G","W"]},{"name":"Sunscorched Divide","cId":["R","W"]},{"name":"Viridescent Bog","cId":["B","G"]}],
    "Dual Reveal Land":[{"name":"Choked Estuary","cId":["B","U"]},{"name":"Foreboding Ruins","cId":["B","R"]},{"name":"Fortified Village","cId":["G","W"]},{"name":"Frostboil Snarl","cId":["R","U"]},{"name":"Furycalm Snarl","cId":["R","W"]},{"name":"Game Trail","cId":["G","R"]},{"name":"Necroblossom Snarl","cId":["B","G"]},{"name":"Port Town","cId":["U","W"]},{"name":"Shineshadow Snarl","cId":["B","W"]},{"name":"Vineglimmer Snarl","cId":["G","U"]}],
    "Dual Refuge Land":[{"name":"Akoum Refuge","cId":["B","R"]},{"name":"Graypelt Refuge","cId":["G","W"]},{"name":"Jwar Isle Refuge","cId":["B","U"]},{"name":"Kazandu Refuge","cId":["G","R"]},{"name":"Sejiri Refuge","cId":["U","W"]}],
    "Dual Sac Draw Land":[{"name":"Botanical Plaza","cId":["G","W"]},{"name":"Racers' Ring","cId":["G","R"]},{"name":"Skybridge Towers","cId":["U","W"]},{"name":"Tramway Station","cId":["B","R"]},{"name":"Waterfront District","cId":["B","U"]}],
    "Dual Slow Fetch Land":[{"name":"Bad River","cId":[]},{"name":"Flood Plain","cId":[]},{"name":"Grasslands","cId":[]},{"name":"Mountain Valley","cId":[]},{"name":"Rocky Tar Pit","cId":[]}],
    "Dual Storage Land":[{"name":"Calciform Pools","cId":["U","W"]},{"name":"Dreadship Reef","cId":["B","U"]},{"name":"Fungal Reaches","cId":["G","R"]},{"name":"Molten Slagheap","cId":["B","R"]},{"name":"Saltcrusted Steppe","cId":["G","W"]}],
    "Dual Tainted Land":[{"name":"Tainted Field","cId":["B","W"]},{"name":"Tainted Isle","cId":["B","U"]},{"name":"Tainted Peak","cId":["B","R"]},{"name":"Tainted Wood","cId":["B","G"]}],
    "Dual Tango Land":[{"name":"Canopy Vista","cId":["G","W"]},{"name":"Cinder Glade","cId":["G","R"]},{"name":"Prairie Stream","cId":["U","W"]},{"name":"Smoldering Marsh","cId":["B","R"]},{"name":"Sunken Hollow","cId":["B","U"]}],
    "Dual Tapped Invasion Land":[{"name":"Coastal Tower","cId":["U","W"]},{"name":"Elfhame Palace","cId":["G","W"]},{"name":"Salt Marsh","cId":["B","U"]},{"name":"Shivan Oasis","cId":["G","R"]},{"name":"Urborg Volcano","cId":["B","R"]}],
    "Dual Tapped Land":[{"name":"Cinder Barrens","cId":["B","R"]},{"name":"Forsaken Sanctuary","cId":["B","W"]},{"name":"Foul Orchard","cId":["B","G"]},{"name":"Highland Lake","cId":["R","U"]},{"name":"Meandering River","cId":["U","W"]},{"name":"Stone Quarry","cId":["R","W"]},{"name":"Submerged Boneyard","cId":["B","U"]},{"name":"Timber Gorge","cId":["G","R"]},{"name":"Tranquil Expanse","cId":["G","W"]},{"name":"Woodland Stream","cId":["G","U"]}],
    "Dual Tapped Snow Land":[{"name":"Arctic Flats","cId":["G","W"]},{"name":"Boreal Shelf","cId":["U","W"]},{"name":"Frost Marsh","cId":["B","U"]},{"name":"Highland Weald","cId":["G","R"]},{"name":"Tresserhorn Sinks","cId":["B","R"]}],
    "Dual Verge Land":[{"name":"Blazemire Verge","cId":["B","R"]},{"name":"Bleachbone Verge","cId":["B","W"]},{"name":"Floodfarm Verge","cId":["U","W"]},{"name":"Gloomlake Verge","cId":["B","U"]},{"name":"Hushwood Verge","cId":["G","W"]},{"name":"Riverpyre Verge","cId":["R","U"]},{"name":"Sunbillow Verge","cId":["R","W"]},{"name":"Thornspire Verge","cId":["G","R"]},{"name":"Wastewood Verge","cId":["B","G"]},{"name":"Willowrush Verge","cId":["G","U"]}],
    "Dual Tempest Land":[{"name":"Caldera Lake","cId":["R","U"]},{"name":"Cinder Marsh","cId":["B","R"]},{"name":"Mogg Hollows","cId":["G","R"]},{"name":"Pine Barrens","cId":["B","G"]},{"name":"Rootwater Depths","cId":["B","U"]},{"name":"Salt Flats","cId":["B","W"]},{"name":"Scabland","cId":["R","W"]},{"name":"Skyshroud Forest","cId":["G","U"]},{"name":"Thalakos Lowlands","cId":["U","W"]},{"name":"Vec Townships","cId":["G","W"]}],
    "Tri New Capenna Fetch Land":[{"name":"Brokers Hideout","cId":[]},{"name":"Cabaretti Courtyard","cId":[]},{"name":"Maestros Theater","cId":[]},{"name":"Obscura Storefront","cId":[]},{"name":"Riveteers Overlook","cId":[]}],
    "Tri Homelands Land":[{"name":"An-Havva Township","cId":["G","R","W"]},{"name":"Aysen Abbey","cId":["G","U","W"]},{"name":"Castle Sengir","cId":["B","R","U"]},{"name":"Koskun Keep","cId":["B","G","R"]},{"name":"Wizards' School","cId":["B","U","W"]}],
    "Tri Alara Fetch Land":[{"name":"Bant Panorama","cId":[]},{"name":"Esper Panorama","cId":[]},{"name":"Grixis Panorama","cId":[]},{"name":"Jund Panorama","cId":[]},{"name":"Naya Panorama","cId":[]}],
    "Tri Invasion Land":[{"name":"Ancient Spring","cId":["B","U","W"]},{"name":"Geothermal Crevice","cId":["B","G","R"]},{"name":"Irrigation Ditch","cId":["G","U","W"]},{"name":"Sulfur Vent","cId":["B","R","U"]},{"name":"Tinder Farm","cId":["G","R","W"]}],
    "Tri Lair Land":[{"name":"Crosis's Catacombs","cId":["B","R","U"]},{"name":"Darigaaz's Caldera","cId":["B","G","R"]},{"name":"Dromar's Cavern","cId":["B","U","W"]},{"name":"Rith's Grove","cId":["G","R","W"]},{"name":"Treva's Ruins","cId":["G","U","W"]}],
    "Tri Land (Extras)":[{"name":"Crypt of the Eternals","cId":["B","R","U"]},{"name":"Murmuring Bosk","cId":["B","G","W"]},{"name":"Tournament Grounds","cId":["B","R","W"]}],
    "Cave Land":[{"name":"Brass's Tunnel-Grinder // Tecutlan, the Searing Rift","cId":["R"]},{"name":"Captivating Cave","cId":[]},{"name":"Cavernous Maw","cId":[]},{"name":"Dowsing Device // Geode Grotto","cId":["R"]},{"name":"Echoing Deeps","cId":[]},{"name":"Forgotten Monument","cId":[]},{"name":"Grasping Shadows // Shadows' Lair","cId":["B"]},{"name":"Hidden Cataract","cId":["U"]},{"name":"Hidden Courtyard","cId":["W"]},{"name":"Hidden Necropolis","cId":["B"]},{"name":"Hidden Nursery","cId":["G"]},{"name":"Hidden Volcano","cId":["R"]},{"name":"Pit of Offerings","cId":[]},{"name":"Promising Vein","cId":[]},{"name":"Sunken Citadel","cId":[]},{"name":"Sunken Palace","cId":["U"]},{"name":"Tarrian's Journal // The Tomb of Aclazotz","cId":["B"]},{"name":"Twists and Turns // Mycoid Maze","cId":["G"]},{"name":"Urza's Cave","cId":[]},{"name":"Volatile Fault","cId":[]}],
    "Desert Land":[{"name":"Abraded Bluffs","cId":["R","W"]},{"name":"Arid Archway","cId":[]},{"name":"Bristling Backwoods","cId":["G","R"]},{"name":"Bucolic Ranch","cId":[]},{"name":"Cactus Preserve","cId":[]},{"name":"Conduit Pylons","cId":[]},{"name":"Cradle of the Accursed","cId":[]},{"name":"Creosote Heath","cId":["G","W"]},{"name":"Desert","cId":[]},{"name":"Desert Cenote","cId":[]},{"name":"Desert of the Fervent","cId":["R"]},{"name":"Desert of the Glorified","cId":["B"]},{"name":"Desert of the Indomitable","cId":["G"]},{"name":"Desert of the Mindful","cId":["U"]},{"name":"Desert of the True","cId":["W"]},{"name":"Dunes of the Dead","cId":[]},{"name":"Endless Sands","cId":[]},{"name":"Eroded Canyon","cId":["R","U"]},{"name":"Festering Gulch","cId":["B","G"]},{"name":"Forlorn Flats","cId":["B","W"]},{"name":"Grasping Dunes","cId":[]},{"name":"Hashep Oasis","cId":["G"]},{"name":"Hostile Desert","cId":[]},{"name":"Ifnir Deadlands","cId":["B"]},{"name":"Ipnu Rivulet","cId":["U"]},{"name":"Jagged Barrens","cId":["B","R"]},{"name":"Lazotep Quarry","cId":[]},{"name":"Lonely Arroyo","cId":["U","W"]},{"name":"Lush Oasis","cId":["G","U"]},{"name":"Mirage Mesa","cId":[]},{"name":"Painted Bluffs","cId":[]},{"name":"Ramunap Ruins","cId":["R"]},{"name":"Sandstorm Verge","cId":[]},{"name":"Scavenger Grounds","cId":[]},{"name":"Shefet Dunes","cId":["W"]},{"name":"Soured Springs","cId":["B","U"]},{"name":"Sunscorched Desert","cId":[]},{"name":"Survivors' Encampment","cId":[]}],
    "Gate Land":[{"name":"A-Thran Portal","cId":[]},{"name":"Azorius Guildgate","cId":["U","W"]},{"name":"Baldur's Gate","cId":[]},{"name":"Basilisk Gate","cId":[]},{"name":"Black Dragon Gate","cId":["B"]},{"name":"Boros Guildgate","cId":["R","W"]},{"name":"Citadel Gate","cId":["W"]},{"name":"Cliffgate","cId":["R"]},{"name":"Dimir Guildgate","cId":["B","U"]},{"name":"Gate of the Black Dragon","cId":["B"]},{"name":"Gate to Manorborn","cId":["G"]},{"name":"Gate to Seatower","cId":["U"]},{"name":"Gate to the Citadel","cId":["W"]},{"name":"Gate to Tumbledown","cId":["R"]},{"name":"Gateway Plaza","cId":[]},{"name":"Golgari Guildgate","cId":["B","G"]},{"name":"Gond Gate","cId":[]},{"name":"Gruul Guildgate","cId":["G","R"]},{"name":"Heap Gate","cId":[]},{"name":"Izzet Guildgate","cId":["R","U"]},{"name":"Manor Gate","cId":["G"]},{"name":"Orzhov Guildgate","cId":["B","W"]},{"name":"Rakdos Guildgate","cId":["B","R"]},{"name":"Sea Gate","cId":["U"]},{"name":"Selesnya Guildgate","cId":["G","W"]},{"name":"Simic Guildgate","cId":["G","U"]},{"name":"Talon Gates of Madara","cId":[]},{"name":"The Black Gate","cId":["B"]},{"name":"Thran Portal","cId":[]}],
    "Locus Land":[{"name":"Cloudpost","cId":[]},{"name":"Glimmerpost","cId":[]},{"name":"Trenchpost","cId":[]}],
    "Snow Land":[{"name":"Alpine Meadow","cId":["R","W"]},{"name":"Arctic Flats","cId":["G","W"]},{"name":"Arctic Treeline","cId":["G","W"]},{"name":"Boreal Shelf","cId":["U","W"]},{"name":"Dark Depths","cId":[]},{"name":"Faceless Haven","cId":[]},{"name":"Frost Marsh","cId":["B","U"]},{"name":"Frostwalk Bastion","cId":[]},{"name":"Glacial Floodplain","cId":["U","W"]},{"name":"Highland Forest","cId":["G","R"]},{"name":"Highland Weald","cId":["G","R"]},{"name":"Ice Tunnel","cId":["B","U"]},{"name":"Mouth of Ronom","cId":[]},{"name":"Rimewood Falls","cId":["G","U"]},{"name":"Scrying Sheets","cId":[]},{"name":"Shimmerdrift Vale","cId":[]},{"name":"Snow-Covered Forest","cId":["G"]},{"name":"Snow-Covered Island","cId":["U"]},{"name":"Snow-Covered Mountain","cId":["R"]},{"name":"Snow-Covered Plains","cId":["W"]},{"name":"Snow-Covered Swamp","cId":["B"]},{"name":"Snow-Covered Wastes","cId":[]},{"name":"Snowfield Sinkhole","cId":["B","W"]},{"name":"Sulfurous Mire","cId":["B","R"]},{"name":"Tresserhorn Sinks","cId":["B","R"]},{"name":"Volatile Fjord","cId":["R","U"]},{"name":"Woodland Chasm","cId":["B","G"]}],
    "Sphere Land":[{"name":"Mirrex","cId":[]},{"name":"The Autonomous Furnace","cId":["R"]},{"name":"The Dross Pits","cId":["B"]},{"name":"The Fair Basilica","cId":["W"]},{"name":"The Hunter Maze","cId":["G"]},{"name":"The Monumental Facade","cId":[]},{"name":"The Mycosynth Gardens","cId":[]},{"name":"The Seedcore","cId":[]},{"name":"The Surgical Bay","cId":["U"]}],
    "Urza Land":[{"name":"Urza's Cave","cId":[]},{"name":"Urza's Factory","cId":[]},{"name":"Urza's Fun House","cId":[]},{"name":"Urza's Mine","cId":[]},{"name":"Urza's Power Plant","cId":[]},{"name":"Urza's Saga","cId":[]},{"name":"Urza's Tower","cId":[]},{"name":"Urza's Workshop","cId":[]}]
}





















































































