export const categoryOptions = [
    { value: '',    label: 'None'    },
    //Card Types
    { value: '+-t%3Aland',         label: 'Non-Land'       },
    { value: '+t%3Aartifact',      label: 'Artifacts'      },
    { value: '+t%3Acreature',      label: 'Creatures'      },
    { value: '+t%3Aenchantment',   label: 'Enchantments'   },
    { value: '+t%3Aland',          label: 'Lands'          },
    { value: '+t%3Aplaneswalker',  label: 'Planeswalkers'  },
    { value: '+t%3Abattle',        label: 'Battles'        },
    //Land Types
    { value: '+is%3Afetchland',    label: 'Fetch Lands'    },
    { value: '+is%3Ashockland',    label: 'Shock Lands'    },
    { value: '+is%3Acanopyland',   label: 'Canopy Lands'   },
    { value: '+is%3Abounceland',   label: 'Bounce Lands'   },
    { value: '+is%3Apainland',     label: 'Pain Lands'     },
    { value: '+is%3Acheckland',    label: 'Check Lands'    },
    { value: '+is%3Afilterland',   label: 'Filter Lands'   },
    { value: '+is%3Ascryland',     label: 'Scry Lands'     },
    { value: '+is%3Adual',         label: 'Dual Lands'     },
    { value: '+is%3Atriland',      label: 'Tri Lands'      },
    { value: '+is%3Atricycleland', label: 'Triomes'        },
    { value: '+is%3Atricycleland', label: 'Tricycle Lands' },
    { value: '+is%3Atangoland',    label: 'Tango Lands'    },
    { value: '+is%3Acreatureland', label: 'Man Lands'      },
    { value: '+is%3Acreatureland', label: 'Creature Lands' },
    { value: '+is%3Aslowland',     label: 'Slow Lands'     },
    { value: '+is%3Afastland',     label: 'Fast Lands'     },
    { value: '+is%3Acycleland',    label: 'Bicycle Lands'  },
    { value: '+is%3Amodal_dfc+t%3Aland',label: 'MDFC Lands'},
    //Catagories
    { value: '+otag%3Aboardwipe',  label: 'Board Wipe'     },
    { value: '+otag%3Aboardwipe',  label: 'Board Clear'    },
    { value: '+otag%3Aboardwipe',  label: 'Mass Removal'   },
    { value: '+is%3Adfc+-t%3Aland',label: 'Non-Land DFC'   },
    { value: '+t%3Aattraction',    label: 'Attracion'      },
    { value: '+set%3ASUNF',        label: 'Sticker Cards'  },
    { value: '+t%3Aplane',         label: 'Plane Cards'    },
    { value: '+t%3Avanguard',      label: 'Vanguards'      },
    { value: '+t%3Ascheme',        label: 'Schemes'        },
    { value: '+t%3Aphenomenon',    label: 'Phenomenons'    },
    { value: '+f%3Apauper',        label: 'Pauper Legal'   },
    { value: '+is%3Acommander',    label: 'Commanders'     },
    //Creature Types
    { value: '+t%3Agoblin',        label: 'Goblins'        },
    { value: '+t%3Azombie',        label: 'Zombies'        },
    { value: '+t%3Adragon',        label: 'Dragons'        },
    { value: '+t%3Awizard',        label: 'Wizards'        },
    { value: '+t%3Adinosaur',      label: 'Dinosaurs'      },
    { value: '+t%3Ahuman',         label: 'Humans'         },
    { value: '+t%3Aelf',           label: 'Elves'          },
    { value: '+t%3Avampire',       label: 'Vampires'       },
    { value: '+t%3Aangel',         label: 'Angels'         },
    { value: '+t%3Aphyrexian',     label: 'Phyrexian'      },
    { value: '+t%3Asliver',        label: 'Slivers'        },
    { value: '+t%3Acat',           label: 'Cats'           },
    { value: '+t%3Amerfolk',       label: 'Merfolk'        },
    { value: '+t%3Aknight',        label: 'Knights'        },
    { value: '+t%3Aspirit',        label: 'Spirits'        },
    { value: '+t%3Ahorror',        label: 'Horrors'        },
    { value: '+t%3Aeldrazi',       label: 'Eldrazi'        },
    { value: '+t%3Arogue',         label: 'Rogues'         },
    { value: '+t%3Awerewolf',      label: 'Werewolves'     },
    { value: '+t%3Ashapeshifter',  label: 'Shapeshifters'  },
    { value: '+t%3Ahydra',         label: 'Hydra'          },
    { value: '+t%3Asoldier',       label: 'Soldier'        },
];