export const categoryOptions = [
    { value: '',    label: 'None'    },
    //Card Types
    { value: '+-t%3Aland',         label: 'Non-Land'       },
    { value: '+t%3Aartifact',      label: 'Artifacts'      },
    { value: '+t%3Acreature',      label: 'Creatures'      },
    { value: '+t%3Aenchantment',   label: 'Enchantments'   },
    { value: '+t%3Aland',          label: 'Lands'          },
    { value: '+t%3Aplaneswalker',  label: 'Planeswalkers'  },
    { value: '+t%3Abattle',        label: 'Battles'        },
    { value: '+t%3Aaura',          label: 'Aura'           },
    { value: '+t%3Aequipment',     label: 'Equipment'      },
    { value: '+t%3Asnow',          label: 'Snow'           },
    { value: '+t%3Asaga',          label: 'Saga'           },
    { value: '+t%3Avehicle',       label: 'Vehicle'        },
    //Land Types
    { value: '+is%3Afetchland',    label: 'Fetch Lands'    },
    { value: '+is%3Ashockland',    label: 'Shock Lands'    },
    { value: '+is%3Acanopyland',   label: 'Canopy Lands'   },
    { value: '+is%3Abounceland',   label: 'Bounce Lands'   },
    { value: '+is%3Apainland',     label: 'Pain Lands'     },
    { value: '+is%3Acheckland',    label: 'Check Lands'    },
    { value: '+is%3Afilterland',   label: 'Filter Lands'   },
    { value: '+is%3Ascryland',     label: 'Scry Lands'     },
    { value: '+is%3Adual',         label: 'Dual Lands'     },
    { value: '+is%3Atriland',      label: 'Tri Lands'      },
    { value: '+is%3Atangoland',    label: 'Tango Lands'    },
    { value: '+is%3Aslowland',     label: 'Slow Lands'     },
    { value: '+is%3Afastland',     label: 'Fast Lands'     },
    { value: '+is%3Acycleland',    label: 'Bicycle Lands'  },
    { value: '+is%3Amodal_dfc+t%3Aland',label: 'MDFC Lands'},
    { value: '+is%3Acreatureland', label: 'Man Lands / Creature Lands' },
    { value: '+is%3Atricycleland', label: 'Triomes / Tricycle Lands'},
    //Catagories
    { value: '+otag%3Aboardwipe',  label: 'Board Wipe / Board Clear / Mass Removal'},
    { value: '+is%3Adfc+-t%3Aland',label: 'Non-Land DFC'   },
    { value: '+t%3Aattraction',    label: 'Attraction'     },
    { value: '+set%3ASUNF',        label: 'Sticker Cards'  },
    { value: '+t%3Aplane',         label: 'Plane Cards'    },
    { value: '+t%3Avanguard',      label: 'Vanguards'      },
    { value: '+t%3Ascheme',        label: 'Schemes'        },
    { value: '+t%3Aphenomenon',    label: 'Phenomenons'    },
    { value: '+f%3Apauper',        label: 'Pauper Legal'   },
    { value: '+is%3Acommander',    label: 'Commanders'     },
    { value: '+otag%3Ablink',      label: 'Blink / Flicker'},
    { value: '+o%3Acycling',       label: 'Cycling'        },
    { value: '+o%3Acycle',         label: 'Cycling Synergy'},
    { value: '+o%3Ainfect',        label: 'Infect'         },
    { value: '+otag%3Awheel',      label: 'Wheel'          },
    { value: '+o%3Aaffinity',      label: 'Affinity'       },
    { value: '+o%3Alandfall',      label: 'Landfall'       },
    { value: '+otag%3Amana-rock',  label: 'Mana Rock'      },
    { value: '+otag%3Amana-dork',  label: 'Mana Dork'      },
    { value: '+o%3Amill',          label: 'Mill'           },
    { value: '+o%3Azombie',        label: 'Zombie Synergy' },
    { value: '+otag%3Acantrip',    label: 'Cantrip'        },
    { value: '+o%3Aparadox',       label: 'Paradox'        },
    { value: '+o%3A"time travel"', label: 'Time Travel'    },
    { value: '+o%3Asuspend',       label: 'Suspend'        },
    { value: '+o%3Avanishing',     label: 'Vanishing'      },
    { value: '+o%3A"time counter"',label: 'Time Counter'   },
    { value: '+o%3Avote',          label: 'Vote'           },
    { value: '+o%3Adiscard',       label: 'Discard'        },
    { value: '+o%3Amadness',       label: 'Madness'        },
    { value: '+o%3Asticker',       label: 'Sticker Synergy'},
    { value: '+o%3Aninjutsu',      label: 'Ninjutsu'       },
    { value: '+mv%3Aeven',         label: 'Even Cost'      },
    { value: '+mv%3Aodd',          label: 'Odd Cost'       },
    { value: '+m%3A%7Bx%7D',       label: 'X Cost'         },
    { value: '+otag%3Aburn',       label: 'Burn'           },
    { value: '+o%3Acopy',          label: 'Copy'           },
    { value: '+o%3Amagecraft',     label: 'Magecraft'      },
    { value: '+o%3Aflashback',     label: 'Flashback'      },
    { value: '+o%3Ajump-start',    label: 'Jump-Start'     },
    { value: '+o%3Aescape',        label: 'Escape'         },
    { value: '+o%3Adredge',        label: 'Dredge'         },
    { value: '+otag%3Areanimate',  label: 'Reanimate'      },
    { value: '+otag%3Astorm',      label: 'Storm'          },
    { value: '+o%3Amutate',        label: 'Mutate'         },
    { value: '+o%3Aparty',         label: 'Party'          },
    { value: '+o%3Agoad',          label: 'Goad'           },
    { value: '+o%3Asaproling',     label: 'Saproling'      },
    { value: '+o%3Aforetell',      label: 'Foretell'       },
    { value: '+o%3Amonarch',       label: 'Monarch'        },
    { value: '+o%3Acascade',       label: 'Cascade'        },
    { value: '+(o%3Afight or %3Afights)', label: 'Fight'   },
    { value: '+(o%3Aclue or o%3Ainvestigate)',label: 'Clue'},
    { value: '+o%3Ainvestigate',   label: 'Investigate'    },
    { value: '+otag%3Agroup-hug',  label: 'Group Hug'      },
    { value: '+o%3A"counter target"',label: 'Counterspells'},
    { value: '+o%3Apopulate',      label: 'Populate'       },
    { value: '+o%3Aflash',         label: 'Flash'          },
    { value: '+o%3Adevotion',      label: 'Devotion'       },
    { value: '+o%3A"extra turn"',  label: 'Extra Turn'     },
    { value: '+o%3Aconvoke',       label: 'Convoke'        },
    { value: '+o%3Aprowess',       label: 'Prowess'        },
    { value: '+otag%3Aramp',       label: 'Ramp'           },
    { value: '+o%3A{e}',           label: 'Energy'         },
    { value: '+o%3Ainsect',        label: 'Insect Synergy' },
    { value: '+o%3Athopter',      label: 'Thopter Synergy' },
    { value: '+o%3Adefender',      label: 'Defender'       },
    { value: '+o%3Aexalted',       label: 'Exalted'        },
    { value: '+otag%3Apillowfort', label: 'Pillow Fort'    },

    // Long Text Catagories 
    { value: '+(o%3Adestroy or o%3Aexile) +((o%3Atarget and o%3Apermanent) or +o%3A"permanents")', label: 'Permanent Destruction / Permanent Removal'},
    { value: '+((o%3Adestroy +(o%3A"target land" or +o%3A"lands")) or otag%3Aremoval-land-destroy)', label: 'Land Destruction / Land Removal'},
    { value: '+(o%3A{t} and o%3Adeal and o%3Adamage and -o%3A"damage to you")', label: 'Pingers' },
    { value: '+otag%3Abounce', label: 'Bounce / Return to Hand' },
    { value: '+(o%3Adraw and (o%3Acard or o%3Acards))', label: 'Card Draw' },
    { value: '+(o%3Amorph or o%3A"face down")', label: 'Morph / Face Down'},
    { value: '+o%3A"additional combat"', label: 'Extra Combat' },
    { value: '+otag%3Acombat-manipulation', label: 'Combat Manipulation' },
    { value: '+o%3Aflying +(t%3Acreature or t%3Avehicle)', label: 'Flying' },
    { value: '+o%3Ahexproof +(t%3Acreature or t%3Avehicle)', label: 'Hexproof' },
    { value: '+o%3Adeathtouch +(t%3Acreature or t%3Avehicle)', label: 'Deathtouch' },
    { value: '+o%3Atrample +(t%3Acreature or t%3Avehicle)', label: 'Trample' },
    { value: '+o%3Ashroud +(t%3Acreature or t%3Avehicle)', label: 'Shroud' },
    { value: '+o%3Aislandwalk +(t%3Acreature or t%3Avehicle)', label: 'Islandwalk' },
    { value: '+o%3Aswampwalk +(t%3Acreature or t%3Avehicle)', label: 'Swampwalk' },
    { value: '+o%3A"first strike" +(t%3Acreature or t%3Avehicle)', label: 'First Strike' },
    { value: '+o%3A"double strike" +(t%3Acreature or t%3Avehicle)', label: 'Double Strike' },
    { value: '+otag%3Areanimate +o%3Acreature',  label: 'Reanimate Creature'},
    { value: '+otag%3Areanimate +(o%3Aenchant or o%3Aartifact or o%3Apermanent or o%3Aplaneswalker or o%3Aland)',  label: 'Reanimate Non-Creature'},
    { value: '+otag%3Acards-in-graveyard-matter', label: 'Graveyard Synergy' },
    { value: '+o%3Acopy +o%3Aspell',label:'Copy Spell'     },
    { value: '+otag%3Acast-from-graveyard', label: 'Cast From Graveyard'},
    { value: '+o%3A"would deal damage" -o%3Aprevent -id<%3DW', label: 'Burn Synergy' },
    { value: '+o%3A"top card" -o%3A"exile the top card"', label: 'Top Card' },
    { value: '+otag%3Asynergy-vote', label: 'Voting Synergy' },
    { value: '+o%3Aequipment',   label: 'Equipment Synergy'  },
    { value: '+otag%3Abirthing-pod', label: 'Pod'            },
    { value: '+otag%3Abirthing-pod', label: 'Birthing Pod'   },
    { value: '+otag%3Ax-cost-matters', label: 'X Cost Synergy' },
    { value: '+(o%3A"whenever you discard" or o%3A"whenever an opponent discards")', label: 'Discard Synergy'},
    { value: '+o%3A"villainous choice"', label: 'Villainous Choice' },
    { value: '+(otag%3Asynergy-exile or otag%3Asynergy-exile-cast or o%3Aparadox)', label: 'Exile Synergy' },
    { value: '+(o%3Achangeling  or o%3A"every creature type")', label: 'Changeling' },
    { value: '+o%3Avehicle -t%3Avehicle', label: 'Vehicle Synergy' },
    { value: '+o%3Aattraction -t%3Aattraction', label: 'Attraction Synergy'},
    { value: '+o%3Aplaneswalker -o%3Adamage',  label: 'Planeswalker Synergy'},
    { value: '+(o%3A"whenever you cast" and (o%3A"instant" or o%3Asorcery))', label: 'Spellslinger' },
    { value: '+(o%3A"sacrifice%3A" or o%3A"whenever you sacrifice")', label: 'Sacrifice'},
    { value: '+(o%3Acreate and (o%3Atoken or o%3Atokens))', label: 'Token'},
    { value: '+(o%3Acounter or o%3Acounters)',     label: 'Counter'  },
    { value: '+(o%3A"%2B1%2F%2B1 counter" or o%3A"%2B1%2F%2B1 counters")',     label: '+1/+1 Counter'  },
    { value: '+(o%3A"%2D1%2F%2D1 counter" or o%3A"%2D1%2F%2D1 counters")',     label: '-1/-1 Counter'  },
    { value: '+((o%3Acounter or o%3Acounters) and (o%3A"whenever one or more" or o%3A"if one or more"))', label: '+1/+1 Counter Synergy' },
    { value: '+(o%3A"gain life" or o%3A"gains life")', label: 'Lifegain' },
    { value: '+(o%3A"whenever you gain life" or o%3A"whenever a player gains life" or o%3A"if you would gain life")', label: 'Lifegain Synergy' },
    { value: '+(o%3A"create a treasure" or o%3A"create treasures")', label: 'Treasure'},

    //Creature Types
    { value: '+t%3Agoblin',        label: 'Goblins'        },
    { value: '+t%3Azombie',        label: 'Zombies'        },
    { value: '+t%3Adragon',        label: 'Dragons'        },
    { value: '+t%3Awizard',        label: 'Wizards'        },
    { value: '+t%3Adinosaur',      label: 'Dinosaurs'      },
    { value: '+t%3Ahuman',         label: 'Humans'         },
    { value: '+t%3Aelf',           label: 'Elves'          },
    { value: '+t%3Avampire',       label: 'Vampires'       },
    { value: '+t%3Aangel',         label: 'Angels'         },
    { value: '+t%3Aphyrexian',     label: 'Phyrexian'      },
    { value: '+t%3Asliver',        label: 'Slivers'        },
    { value: '+t%3Acat',           label: 'Cats'           },
    { value: '+t%3Amerfolk',       label: 'Merfolk'        },
    { value: '+t%3Aknight',        label: 'Knights'        },
    { value: '+t%3Aspirit',        label: 'Spirits'        },
    { value: '+t%3Ahorror',        label: 'Horrors'        },
    { value: '+t%3Aeldrazi',       label: 'Eldrazi'        },
    { value: '+t%3Awarrior',       label: 'Warriors'       },
    { value: '+t%3Acleric',        label: 'Clerics'        },
    { value: '+t%3Arogue',         label: 'Rogues'         },
    { value: '+t%3Awerewolf',      label: 'Werewolves'     },
    { value: '+t%3Ashapeshifter',  label: 'Shapeshifters'  },
    { value: '+t%3Ahydra',         label: 'Hydras'         },
    { value: '+t%3Asoldier',       label: 'Soldiers'       },
    { value: '+t%3Ashrine',        label: 'Shrines'        },
    { value: '+t%3Awall',          label: 'Walls'          },
    { value: '+t%3Aninja',         label: 'Ninjas'         },
    { value: '+t%3Atreefolk',      label: 'Treefolk'       },
    { value: '+t%3Afungus',        label: 'Fungus'         },
    { value: '+t%3Ainsect',        label: 'Insects'        },
    { value: '+t%3Athopter',       label: 'Thopters'       },
    { value: '+(t%3Awarrior or t%3Awizard or t%3Arogue or t%3Acleric) ', label: 'Party Members' },
];